/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MyComponent {
      'first': string;
      'last': string;
    }
  }

  interface HTMLMyComponentElement extends StencilComponents.MyComponent, HTMLStencilElement {}

  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
  }
  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-component': JSXElements.MyComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface MyComponentAttributes extends HTMLAttributes {
      'first'?: string;
      'last'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface MyCounter {
      'start': number;
      'step': number;
    }
  }

  interface HTMLMyCounterElement extends StencilComponents.MyCounter, HTMLStencilElement {}

  var HTMLMyCounterElement: {
    prototype: HTMLMyCounterElement;
    new (): HTMLMyCounterElement;
  };
  interface HTMLElementTagNameMap {
    'my-counter': HTMLMyCounterElement;
  }
  interface ElementTagNameMap {
    'my-counter': HTMLMyCounterElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-counter': JSXElements.MyCounterAttributes;
    }
  }
  namespace JSXElements {
    export interface MyCounterAttributes extends HTMLAttributes {
      'start'?: number;
      'step'?: number;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface MyDemo {
      'name': string;
    }
  }

  interface HTMLMyDemoElement extends StencilComponents.MyDemo, HTMLStencilElement {}

  var HTMLMyDemoElement: {
    prototype: HTMLMyDemoElement;
    new (): HTMLMyDemoElement;
  };
  interface HTMLElementTagNameMap {
    'my-demo': HTMLMyDemoElement;
  }
  interface ElementTagNameMap {
    'my-demo': HTMLMyDemoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-demo': JSXElements.MyDemoAttributes;
    }
  }
  namespace JSXElements {
    export interface MyDemoAttributes extends HTMLAttributes {
      'name'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;