/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MyCounter {
      'start': number;
      'step': number;
    }
  }

  interface HTMLMyCounterElement extends StencilComponents.MyCounter, HTMLStencilElement {}

  var HTMLMyCounterElement: {
    prototype: HTMLMyCounterElement;
    new (): HTMLMyCounterElement;
  };
  interface HTMLElementTagNameMap {
    'my-counter': HTMLMyCounterElement;
  }
  interface ElementTagNameMap {
    'my-counter': HTMLMyCounterElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-counter': JSXElements.MyCounterAttributes;
    }
  }
  namespace JSXElements {
    export interface MyCounterAttributes extends HTMLAttributes {
      'onChange'?: (event: CustomEvent) => void;
      'start'?: number;
      'step'?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;